### ISSUE TITLE
tests in TypeScript (.ts files) lack stack traces

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8662] opened 2023-12-14 22:21 UTC
## What is the Problem Being Solved?

The `boot` tests run `.ts` files in Ava using `--loader=tsx`. This works but due to the Endo hardening the stack traces lose line numbers. (Transpiled files are treat as being all in one line)

**To observe**
```
cd packages/boot
# edit a test file to induce an exception
yarn test yarn test test/bootstrapTests/test-addAssets.ts
```
See the `.ts` files in the stack trace all report line 1. E.g.,
```
  › Node.js v20.11.0
  › runPackageScript (packages/boot/tools/supports.ts:1:2676)
  › async Object.buildAndExtract [as buildProposal] (packages/boot/tools/supports.ts:1:3672)
  › async packages/boot/test/bootstrapTests/test-addAssets.ts:1:435
```

## Description of the Design

https://github.com/endojs/endo/issues/1798 was one hypothesis but may not solve the above.

## Security Considerations
n/a
## Scaling Considerations
n/a
## Test Plan

Verify manually that stack traces have full line numbers.

## Upgrade Considerations
n/a

**Comment by dckc** [comment] 2024-02-13 21:02
This is impacting me today. Not a big deal, but...

```
  use IBC callbacks after upgrade
  Value is not truthy:

  undefined

  › packages/boot/test/bootstrapTests/test-vats-restart.ts:1:4790
```

**Comment by erights** [comment] 2024-03-01 23:21
I don't understand what's causing this, so I don't know if #2109 would help.

@turadg @dckc how can I reproduce?

**Comment by mhofman** [comment] 2024-03-02 15:44
I know what the problem is. Mark I can walk you through my potential fix this week.

**Comment by turadg** [comment] 2024-03-04 14:53
@erights I've added repro steps to the body.

**Comment by erights** [comment] 2024-07-12 21:11
This is a bug in endo, not in agoric-sdk. Now filed as https://github.com/endojs/endo/issues/2348 . Feel free to close out this one as subsumed by that one.

**Comment by erights** [comment] 2024-07-12 21:12
Thanks for the repro steps! I'll try to reproduce this.

**Comment by erights** [comment] 2024-07-12 21:14
I assigned that one to myself. I am also assigning this to myself, and closing this one as subsumed by that one.

**Comment by turadg** [comment] 2024-07-12 21:20
I have this problem in agoric-sdk so I'll keep the ticket open until it's solved.

**Comment by erights** [comment] 2024-07-12 21:22
Ok. Keep it assigned to me.

**Closed as completed** 2024-07-19 08:55 UTC
Labels: enhancement, tooling, test, devex
