### ISSUE TITLE
Ensure the chain still has horsepower for many more items

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8189] opened 2023-08-15 12:59 UTC
## What is the Problem Being Solved?
Prior to Reference Partner go live we need a firm "Belief the chain still has horsepower for many more items to run". From [MN2 Reference Partner Go Live Checklist](https://docs.google.com/document/d/1UDZPHXK9ZylTHE4CKyPrwej18lK1j2BquuRw96fnuzY/edit?usp=sharing)

**Comment by dckc** [comment] 2023-08-30 14:15
Is this specific to Kryha? Conservatively, I suppose I should infer that it is.

**Comment by aj-agoric** [comment] 2023-09-07 21:45
@dckc  yes, this is part of our Partner's Go Live Checklist so specific to Kryha / Kread here.  I assume I should assign this to you?

**Comment by dckc** [comment] 2023-09-07 22:51
I hope there's somebody more experienced than I in how to do this. @turadg ? @warner ?

How is it different from #8196?

This doesn't seem to be in [a more recent version of the checklist](https://github.com/Agoric/agoric-sdk/discussions/8280).

**Comment by turadg** [comment] 2023-09-07 22:57
I think it's effectively a dupe of 8196, written against an earlier version of the checklist.

**Closed as not planned by turadg** 2023-09-07 22:57 UTC
Labels: enhancement, performance
