### ISSUE TITLE
vaults chain doesn't support pismo wallet

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#6993] opened 2023-02-13 20:20 UTC
## Describe the bug
Unable to load a provisioned wallet in wallet.agoric.app due to `Error in wallet backend: Cannot read properties of undefined (reading 'find')`

## To Reproduce
1. wallet.agoric.app with keplr key gov1
2. configure ollinet
3. provision wallet
4. error pops up

## Expected behavior
no error, with a list of purses

<img width="684" alt="Screenshot 2023-02-13 at 12 18 29 PM" src="https://user-images.githubusercontent.com/22369/218566064-2ee83289-f970-4bda-83eb-6057368e5821.png">
<img width="599" alt="Screenshot 2023-02-13 at 12 18 24 PM" src="https://user-images.githubusercontent.com/22369/218566070-5e9cd09a-e354-4d5d-baac-13dd3fa61483.png">
<img width="611" alt="Screenshot 2023-02-13 at 12 18 07 PM" src="https://user-images.githubusercontent.com/22369/218566072-903a8f2e-f448-404f-b48c-beb759f84585.png">

**Comment by samsiegart** [comment] 2023-02-13 21:05
We'll have to upgrade wallet.agoric.app when we upgrade the chain. For now try https://main.wallet-app.pages.dev/wallet/ for a version that's in sync with current master

**Comment by arirubinstein** [comment] 2023-02-13 21:14
testing:

https://bafybeiayv363sa5kzowzogxcc4fi5igoo4oocw5a5ywquaqafvjdo2xqfu.ipfs.cf-ipfs.com/?wallet=main
and
https://main.wallet-app.pages.dev/wallet/
and
https://app.inter.trade/?network=ollinet

**Comment by dckc** [comment] 2023-02-14 16:54
`o.brands.find(...)` is failing because we no longer provide `o.brands`:

 - #6807 

It's a breaking change, but pretty important for performance / scalability.

The dev wallet has been updated to get the info from `x/bank` and `agoricNames.vbankAsset`:

 - #6788

Do we want to keep this issue open until the chain is updated and the front end is deployed in production? Or close it as "working as designed"? Or something in between?

**Comment by ivanlei** [comment] 2023-04-17 15:28
Expect folks to use the `?wallet=main` workaround

**Comment by dckc** [comment] 2023-04-26 20:08
see also https://github.com/Agoric/dapp-psm/pull/58

**Closed as completed** 2024-06-10 19:00 UTC
Labels: wallet, UI, Dapp & UI Support, vaults_triage
