### ISSUE TITLE
Deploy cosmos PFM on Chain

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8876] opened 2024-02-08 16:06 UTC
## What is the Problem Being Solved?
To use with coming products,  we aim to put cosmos PFM on chain
https://github.com/cosmos/ibc-apps/tree/main/middleware/packet-forward-middleware

**Comment by ivanlei** [comment] 2024-02-09 13:45
## Which version of PFM to use?

### agoric-sdk versions

* go,mod - https://github.com/Agoric/agoric-sdk/blob/master/golang/cosmos/go.mod
* Cosmos-SDK v0.46.16
    * [github.com/cosmos/cosmos-sdk](http://github.com/cosmos/cosmos-sdk) => [github.com/agoric-labs/cosmos-sdk](http://github.com/agoric-labs/cosmos-sdk) v0.46.16-alpha.agoric.1
* IBC-Go v6.2.1
* Tendermint v0.34.29
    * [github.com/tendermint/tendermint](http://github.com/tendermint/tendermint) => [github.com/agoric-labs/cometbft](http://github.com/agoric-labs/cometbft) v0.34.30-alpha.agoric.1

### PFM Versions and Dependencies

* ❌ PFM v8.0.0 - https://github.com/cosmos/ibc-apps/releases/tag/middleware%2Fpacket-forward-middleware%2Fv8.0.0 
    * go-mod - https://github.com/cosmos/ibc-apps/blob/middleware/packet-forward-middleware/v8.0.0/middleware/packet-forward-middleware/go.mod
        * Cosmos-SDK v0.50.1
        * IBC-Go v8.0.0
        * CometBFT v0.38.2
* ❌ PFM v7.1.2 - https://github.com/cosmos/ibc-apps/releases/tag/middleware%2Fpacket-forward-middleware%2Fv7.1.2
    * go.mod - https://github.com/cosmos/ibc-apps/blob/middleware/packet-forward-middleware/v7.1.2/middleware/packet-forward-middleware/go.mod
        * Cosmos-SDK v0.47.5
        * IBC-Go v7.3.1
        * CometBFT v0.37.2
* ✅ PFM v6.1.1 - https://github.com/cosmos/ibc-apps/releases/tag/middleware%2Fpacket-forward-middleware%2Fv6.1.1
    * go.mod - https://github.com/cosmos/ibc-apps/blob/middleware/packet-forward-middleware/v6.1.1/middleware/packet-forward-middleware/go.mod
        * Cosmos-SDK v0.46.15
        * IBC-Go v6.2.0
        * Tendermint v0.34.29

### PFM Important Git Links

* Last commit on v6.1.1 - https://github.com/cosmos/ibc-apps/commit/232c0f1cea39c1dff81507a547e183e305e41ac3
* Branch - https://github.com/cosmos/ibc-apps/tree/middleware/packet-forward-middleware/v6.1.1
* Integration Guide - https://github.com/cosmos/ibc-apps/blob/middleware/packet-forward-middleware/v6.1.1/middleware/packet-forward-middleware/docs/integration.md

**Comment by ivanlei** [comment] 2024-02-13 16:29
Duplicate of https://github.com/Agoric/agoric-sdk/issues/7712

**Closed as completed by ivanlei** 2024-02-13 16:29 UTC
Labels: enhancement
