### ISSUE TITLE
feeDistributor vat is not ugpradable

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#8729] opened 2024-01-09 02:30 UTC
While looking at https://github.com/Agoric/agoric-sdk/pull/8499#issuecomment-1842457715 . and thinking about how v28-feeDistributor would react under upgrade, we noticed that v28-feeDistributor is not ugpradable. 

v23-feeDistributor [has code](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/inter-protocol/src/feeDistributor.js#L92-L98) which talks to the timer service and creates a notifier during `startDistributing`. However this function is [called only from](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/inter-protocol/src/feeDistributor.js#L336) `makeFeeDistributor`, which creates ephemeral `creatorFacet` and `publicFacet` objects (using `Far()`). So this contract instance is not upgradable: if we were to deploy any new version of v23-feeDistributor, these facets would be abandoned, making them unavailable for clients.

Since we can't upgrade v23-feeDistributor, we'll need to replace it, somehow, by convincing any clients to use a different vat, and then terminate the old one.

I didn't find any other tickets describing our plan to replace this code, so I figured I should start a new one.

cc @Chris-Hibbert

**Comment by dckc** [comment] 2024-01-09 20:31
Um... did we miss this one in the bulldozer planning somehow? No... we decided it was OK:

> "cron job" with no important state. can terminated and replaced at will.
 -- https://github.com/Agoric/agoric-sdk/issues/5795

https://github.com/Agoric/agoric-sdk/blob/d3ddae6fa38b289b415d9f1bbbbd83338ad4aed3/packages/builders/scripts/vats/restart-vats.js#L7-L9

I think there are no clients.

**Comment by Chris-Hibbert** [comment] 2024-05-15 16:53
The feeDistributor may only be used by PSM and vat-bank.

**Comment by dckc** [comment] 2024-05-15 17:52
feeDistributor collects from vaultFactory and sends to reserve; so it's a client of those 2.

https://github.com/Agoric/agoric-sdk/blob/1749514b5b69a3112d60293ffc141885e4ff2edd/packages/inter-protocol/src/proposals/econ-behaviors.js#L500-L502

PSM could generate fees, but it doesn't, so we didn't write it up, AFAICT.

feeDistributor 's only client is the time service, I think.

**Comment by Chris-Hibbert** [comment] 2024-05-20 23:22
The feeDistributor does all the work, and knows both the payers and payees. Neither of those has any knowledge of the feeDistributor.

The bootstrapSpace has creatorFacets for the payers, which have a `makeCollectFeesInvitation()` method. It also knows how to make `depositFacets` for the recipients of the funds. 

To replace (not upgrade) the feeDistributor, just create a new one, and register it as the `feeDistributor`
```
  feeDistributorKit.resolve(
    harden({ ...instanceKit, label: 'feeDistributor' }),
  );
  feeDistributorP.resolve(instanceKit.instance);
```

The only current provider of fees is `vaultFactory`, and the recipients are current configured as 
```
      keywordShares: {
        RewardDistributor: 0n,
        Reserve: 1n,
      }
```

**Comment by LuqiPan** [comment] 2024-11-14 17:53
@Chris-Hibbert, this looks to me a duplicate of #10393 and as such, should it be closed?

**Comment by Chris-Hibbert** [comment] 2024-11-14 18:56
@LuqiPan  It has details that weren't reproduced in #10393 

@anilhelvaci, PTAL at this and verify that it doesn't raise any issues that we might have missed in #10453.

**Comment by LuqiPan** [comment] 2024-12-10 17:34
@anilhelvaci ping on above comment/question

**Comment by anilhelvaci** [comment] 2024-12-11 12:36
My understanding is that this issue is concerned about any clients of `feeDistributor` will lose their reference to `feeDistributor` once it is replaced. And asks "Are we covering this issue?". 

I agree with @dckc 's comment [here](https://github.com/Agoric/agoric-sdk/issues/8729#issuecomment-2113121520). With one caveat:

> feeDistributor 's only client is the time service, I think.

I believe this should be the opposite. `feeDistributor` is a client of `timerService` since feeDistributor is the one requesting a notifier from timerService:

https://github.com/Agoric/agoric-sdk/blob/3b478fb9e3fe7ded8dec1e83bab68760571f9071/packages/inter-protocol/src/feeDistributor.js#L94-L97

This brings us to the conclusion that `feeDistributor` has NO clients and it functions with the powers it receives from the bootstrap space. Our current test results comply with this. Here's the scenario we implement to test this:

* Start a new `feeDistributor` with a shorter `collectionInterval` (30 seconds) and override the old one from `bootstrap` space.
* Repeat below steps for three times. This will ensure the fees are coming from the new `feeDistributor` and not the old one as the old one's collectionInterval is 1 hour.
  * Open a vault
  * Use syncTools to wait until `reserve` balance increases

[replaceFeeDistributor.test.js](https://github.com/Agoric/agoric-sdk/blob/master/a3p-integration/proposals/p%3Aupgrade-19/replaceFeeDistributor.test.js) produces expected results.

I believe it's safe to close this ticket. @LuqiPan @Chris-Hibbert

**Closed as completed** 2024-12-11 19:30 UTC
Labels: Inter-protocol, contract-upgrade
