### ISSUE TITLE
Vault reconstitution: vault manager appears to incorrectly assign remaining IST to shortfall in addition to reconstituted vaults

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7474] opened 2023-04-21 19:34 UTC
## What is the Problem Being Solved?
Ran through a reconstitute auction scenario where two vaults should have been reconstituted (issues there filed separately)

From the spreadsheet we were using to track results, we saw the following:
Auction completed with 234.54 IST remaining to fill
Vault manager reconstituted two vaults, one with 100.5 debt and another with 103.515 debt
Shortfall amount should have been 30.525 (234.54 minus the 204.015 debt given to vaults)

However, we saw the reserve shortfall increase by 234.54, suggesting it double counted that debt.  

The liquidation penalty also appears unaccounted for.  The expected amount of excess collateral (i.e., not reconstituted into a vault) was transferred to the reserve, but the total collateral (reconstituted in vault + transferred + sold) sums to less than what the auction started with.  The delta is what was expected for the penalty.

**Comment by Chris-Hibbert** [comment] 2023-04-27 16:17
There are tests that check that the shortfall is reported correctly. (test-vaultLiquidation.js, 'Auction sells all collateral w/shortfall'). I've re-checked it, and it looks like the liquidation code is doing the right thing. There isn't enough detail in this report for me to be able to reproduce the scenario that caused the problem. It doesn't look like the number of vaults being liquidated should make a difference. 

Is there any chance you can make it happen again, and show more of the events that led to this situation?

**Comment by turadg** [comment] 2023-04-28 15:03
Closing for now as can't repro. If we find a repro we can reopen.

**Comment by Chris-Hibbert** [comment] 2023-05-01 16:01
@rowgraus suggested attempting to repro

```
can you confirm behavior based on a test that includes vault reconstitution?
Example:
Auction ends in a reconstitution scenario (i.e., enough of both collateral and debt remaining to reconstitute at least one vault).
Expected behavior:
let’s say 15 ATOM left to sell and 150 debt left to raise at end of auction
one vault is reconstituted with 10 ATOM and 100 IST debt
No other vaults can be reconstituted
5 ATOM sent to reserve
shortfall of 50 sent to reserve
The behavior we believe we saw was a vault reconstituted with 100 debt and shortfall of 150 sent to reserve, double counting the 100 debt (edited) 

```

**Comment by rowgraus** [comment] 2023-05-03 14:12
@Chris-Hibbert were you able to repro with the above info?

**Comment by rowgraus** [comment] 2023-05-10 01:45
Reopening as same behavior observed where vault appears in UI reconstituted without collateral.
<img width="610" alt="image" src="https://github.com/Agoric/agoric-sdk/assets/60824328/80f246c1-ec11-4c26-8b39-96f3a32f0fb6">

**Comment by rowgraus** [comment] 2023-05-15 21:21
I reproduced this on a similar scenario just now:

Gov Param:
Liquidation Margin 150%
Liquidation Padding 25%
Liquidation Penalty 1%
Auction: 105% start price, 65% min price, 5% steps

Bids:
25 IST at 30% discount
75 IST at 22% discount

Vaults: 
15 ATOM, 100 IST debt (100.5 after 0.5% fee)
15 ATOM, 103 IST debt (103.51 after 0.5% fee)
15 ATOM, 105 IST debt (105.52 after 0.5% fee)

Starting price $12.34
Price changed to $9.99 -> all vaults enter liquidation

Collateral entering auction: 45
Debt target: 309.54

Both bids fill.  Auction ends with remaining:
Collateral: 31.4198
Debt: 209.54

Auction successfully/correctly reconstitutes two vaults:
ATOM 14.89, IST 100.5
ATOM 14.89, IST 103.51

Reserve Metrics 
Shortfall Balance = the total debt remaining, **i.e., it doesn't subtract out the debt given back to vault holders**
  shortfallBalance: {
    brand: slotToVal("board0257"),
    value: 209540000n, 

ATOM Balance
  allocations: {
    ATOM: {
      brand: slotToVal("board02152","Alleged: ATOM brand"),
      value: 1309355n,

**Note: ATOM Balances remaining should add to 45**
Sold = 13.585013
Reconstituted = 14.899 +14.896
Reserve Balance = 1.309
Total = 44.689013
Delta = ~0.31

Expected Liquidation Penalty = (309.54) * 1% / 9.99 = 0.309

**Comment by rowgraus** [comment] 2023-05-16 17:53
@Chris-Hibbert were you able to track down the liquidation penalty being unaccounted for as part of the fix too?

**Closed as completed** 2023-05-16 20:21 UTC
Labels: Vaults, vaults_triage

**Comment by Chris-Hibbert** [comment] 2023-05-16 20:45
> were you able to track down the liquidation penalty being unaccounted for as part of the fix too?

I'm hopeful that'll be clear when we come to understand the case [I was trying to explain](https://github.com/Agoric/agoric-sdk/issues/7679#issuecomment-1546396580) in #7679.
