### ISSUE TITLE
"exitOffer tool reclaims stuck payment" timed out waiting for tx to be included in a block

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#10565] opened 2024-11-25 19:26 UTC
## Describe the bug

I'm struggling to land #10530 (for #10391). It's in code that shouldn't be affecting acceptance testing yet.

At [step:10:4370](https://github.com/Agoric/agoric-sdk/actions/runs/11982434558/job/33413400559?pr=10530#step:10:4370), we see:

```
    Error: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
```

Then at [step:10:4372](https://github.com/Agoric/agoric-sdk/actions/runs/11982434558/job/33410486494?pr=10530#step:10:4372):

```
 Error {
    message: 'tryExitOffer failed to reclaim stuck payment  condition failed after 15 retries.',
```

And finally, at [step:10:4329](https://github.com/Agoric/agoric-sdk/actions/runs/11982434558/job/33410486494?pr=10530#step:10:4329):

```
  ✘ [fail]: exitOffer tool reclaims stuck payment Rejected promise returned by test
```

## To Reproduce

run CI on #10530 (intermittently?)

## Expected behavior

no error

## Platform Environment

CI:
`git checkout --progress --force refs/remotes/pull/10530/merge`
-> 8e51eff9cea49e8c2605724efbe66e53865ec795

## Additional context

#10530 (for #10391)

**Comment by dckc** [comment] 2024-11-25 19:29
It passed on the 17th, at [step:10:3981](https://github.com/Agoric/agoric-sdk/actions/runs/11881015730/job/33104861001#step:10:3981) for #10483.

```
2024-11-17T18:31:22.034Z block-manager: block 1619 commit
Object <[Object: null prototype] {}> {
  maxRetries: 15,
  retryIntervalMs: 5000,
  reusePromise: false,
  message: 'tryExitOffer failed to reclaim stuck payment '
}
  ✔ exitOffer tool reclaims stuck payment (3.2s)
```

**Comment by Jorge-Lopes** [comment] 2024-11-26 09:46
Greetings @dckc @turadg,

I’ll add this issue to our backlog so it can be considered for an upcoming sprint.
Would you categorize this as a high-priority ticket, or assign it a lower priority?

**Comment by dckc** [comment] 2024-11-26 16:25
@mfig notes [ExecaError ... hardcoded 10 second durationMs: 10142.694018](https://github.com/Agoric/agoric-sdk/actions/runs/11982434558/job/33413400559?pr=10530#step:10:4357), which is just over a hard-coded 10 second `-bblock` timeout and a related in-progress PR:

 - https://github.com/agoric-labs/cosmos-sdk/pull/423

**Comment by 0xpatrickdev** [comment] 2024-11-26 16:38
This [started to pass](https://github.com/Agoric/agoric-sdk/actions/runs/12025550702/job/33522899495#step:10:4161) in CI so **skipping** until this ticket is prioritized: 
https://github.com/Agoric/agoric-sdk/pull/10329/commits/118bc6a304bdf3e084885653c8d049f446bd2b5a

**Comment by anilhelvaci** [comment] 2024-12-25 15:08
## Investigation
I do have reason to believe the flake we're running into is related to the batched execution fee charged on `gov1`. I can't be 100% sure (yet) because of the following reasons;
* In the logs belonging to when the test was failing, I cannot see IST balance of `gov1` before sending the exit offer.
   https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/a3p-integration/proposals/z%3Aacceptance/wallet.test.js#L63
* As far as I can tell `slog` files do not include beans charged per account so I'm not able to observe `gov1`'s beans being charged.
   **Question: Shouldn't gov1's purse be notified after execution fee is deducted from gov1's IST balance?**
   The natural answer to this is "yes" however I cannot observe any messages going into vat-bank before the offer is picked up. Here's an example image to the slog replay I did:
    
   <img width="1196" alt="image" src="https://github.com/user-attachments/assets/4637add0-b0bb-487f-ac74-4183a94f0766" />

    I expect this IST deduction's notification to arrive as an inbound message to `vat10-bridge`. However, I reckon this is not what we are seeing because, [ChargeBeans](https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/golang/cosmos/x/swingset/keeper/keeper.go#L310) method of `swingset/keeper` uses `bank` module's `SendCoinsFromAccountToModule` instead of its `vbank` equivalent.

    https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/golang/cosmos/x/swingset/keeper/keeper.go#L334-L339
  
   Thoughts? @michaelfig 

## Bug Description Breakdown
### Below error message is NOT related to wallet test
```
    Error: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
```

The failing test in  https://github.com/Agoric/agoric-sdk/actions/runs/11982434558/job/33413400559?pr=10530#step:10:4370 is named  `send invitation via namesByAddress` and not `exitOffer tool reclaims stuck payment`. The failure is due to a `-bblock` time out which there's an on going work on it in https://github.com/agoric-labs/cosmos-sdk/pull/423.

### Last two pieces of logs IS related to wallet test
When looking at the condition in which `retryUntilCondition` operates accordingly (in the subject test), we can see that the IST balances are checked using regular `>` operator instead of [tryIstBalances](https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/a3p-integration/proposals/z%3Aacceptance/test-lib/psm-lib.js#L599) we built to avoid flakes rise from charging IST fees.

## Solution
There's no practical way to reproduce my theory and verify it's indeed the case because;
* The factors that effect accrued IST fee vary a lot. They include
   https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/golang/cosmos/x/swingset/types/default-params.go#L60-L66
* According to my theory, the flake we see above is introduced in a state where;
  * There was already an amount of IST fees accrued for `gov1` that is close to 0.2 IST but not greater
  * Fees arised from `tryExitOffer` made the already accrued fees go beyond 0.2 IST so 0.2 IST is deducted from `gov1`'s IST balance
  * Since the amount of IST reclaimed by `tryExitOffer` is 0,015 IST (15_000 uist), the below condition is never true;
     https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/a3p-integration/proposals/z%3Aacceptance/wallet.test.js#L73

It's pretty difficult to re-create the state described above. So I suggest we get rid of all instances where IST balance is not checked using `tryIstBalances`. I believe this would remove the flake we see here and others that we'll possibly see as the number of tests increase. I've created https://github.com/Agoric/agoric-sdk/issues/10774 to track this. And the flake in subject here is going to be included as a work item over there.

**Closed as completed** 2024-12-26 22:40 UTC
Labels: test, flake

**Comment by dckc** [comment] 2024-12-28 16:28
> Shouldn't gov1's purse be notified after execution fee is deducted from gov1's IST balance?

No.

See https://docs.agoric.com/guides/getting-started/contract-rpc.html#vbank-assets-and-cosmos-bank-balances
