### ISSUE TITLE
Updated Title: Too much excess collateral returned to vaults in Liquidation Flow 1 scenario

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#7346] opened 2023-04-06 17:49 UTC
## What is the Problem Being Solved?

If collateral remains after vaults are liquidated and the debt is covered, the vaultManager distributes the remaining collateral in proportion to the collateral each vault had. In doing so, it processes vaults in order from highest CR to lowest, and stops when it runs out of collateral to return.

## Description of the Design

Instead of proportional to the collateral, it should be in proportion to the collateralization ratio.

## Security Considerations

None

## Scaling Considerations

No consequences.

## Test Plan

update existing tests.

**Comment by Chris-Hibbert** [comment] 2023-04-26 21:55
After discussion, "proportional to CR" isn't what we meant.  The payouts have to be proportional to the vault's collateral. But they can be prioritized by CR, to some extent.

The basic flows are documented in #7123.

If there's no shortfall, we return proportional to the collateral, so order doesn't matter.  If there's no shortfall and no collateral is returned we liquidate all the vaults. if IST remains (this could happen before #7239, and the code is still there) it's distributed proportional to collateral. If collateral remains, we process in order from best to worst, reconstituting as many as we can make whole, and liquidating the rest.

What should change here is that in flow 1 we should process the vaults in order (by CR) and repay each to their max (accounting for penalties) until we run out.

I changed the title.

**Comment by otoole-brendan** [comment] 2023-05-16 16:09
@Chris-Hibbert Looks like liquidation proceeds are still not being distributed as expected - I created https://github.com/Agoric/agoric-sdk/issues/7757 for this last night  but re-opening this ticket may make more sense as we believed this issue would be addressed by this ticket. 

Was able to reproduce a variation of the problem using 3x vaults across 2 different accounts instead of 1 to witness this strange behavior: 

- Created 2x vaults for Gov 1 and 1x vault for Gov2 (per happy path scenario)
- Set bids as per happy path scenario as defined in LIquidation testing document
- Triggered liquidation and watched auction proceed.
- After auction completes - checked all 3 vaults across the 2 accounts - all showed liquidated with 0 collateral to claim (we believe this is a separate issue about post-liquidated vaults reporting state).
- Closed Gov 2 vault in UI -> ATOM balance for Gov 2 did not increase/update - stayed flat at 85 ATOM.
- Closed one of the Gov 1 vaults -> ATOM balance for Gov 1 increased by ~9.35 ATOM from 12472.7209 -> 12482.07 (we this was the vault with the highest CR pre liquidation)
- Closed second Gov 1 vault -> ATOM balance remained flat at 12482.07

Suspect that the system is trying to fill the best vault first but is allowing too much ATOM to be given back.  It should limit the max amount of ATOM received based on #7123 Flow 1 Point 3

Recording available internally

**Comment by otoole-brendan** [comment] 2023-05-16 16:46
https://agoric.zoom.us/rec/share/XUsEl75_KdidIEfKg7g_oirMvYAOJuqx0Dv74ixrt3QHMoRApY7U9RIGHnu9ugCK.EcDdfAnKYyY9o_Ei 
Passcode: E4qFf@G%

**Comment by rowgraus** [comment] 2023-05-16 17:12
@Chris-Hibbert in your note above you say:

"What should change here is that in flow 1 we should process the vaults in order (by CR) and repay each to their max (accounting for penalties) until we run out."

The max needs to also account for how much debt they contributed.  The way I framed this in 7123 was:

"original collateral - collateral covering their share of debt (using average liquidation price) - collateral covering their share of the penalty (their debt / total debt * total penalty)"

**Closed as completed** 2023-05-17 04:56 UTC
Labels: enhancement, Inter-protocol, Vaults, vaults_triage
