### ISSUE TITLE
Verify that oracles re-sync after priceFeeds update

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#9885] opened 2024-08-13 16:58 UTC
## What is the Problem Being Solved?

The [SimplyStaking oracle software](https://github.com/SimplyStaking/agoric-cl-middleware) tracks the roundId required by our priceFeeds when submitting price updates. When we replace the priceFeeds, (#9483, #9584), the new priceFeeds will start with a roundId of 0. There appears to be code in the oracles that checks the roundId in vstorage.
 
## Description of the Design

Run a test on mainfork (#9866), Once the priceFeeds are setup, accept new invitations and verify that the oracles switch to the new feeds, and use the correct roundId. If they don't do so already, fix the oracle code so this will work.

## Security Considerations

immaterial.

## Scaling Considerations

N/A.

**Comment by Chris-Hibbert** [comment] 2024-08-20 00:10
duplicate of #9886

**Closed as completed by Chris-Hibbert** 2024-08-20 00:10 UTC
