### ISSUE TITLE
xsnap should exit quietly upon command pipe EOF

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4103] opened 2021-11-19 23:24 UTC
## What is the Problem Being Solved?

@mhofman and I were examining some logs of the load generator, and noticed that when the kernel is shut down (SIGTERM to the kernel process), stderr is immediately filled with a bunch of error messages from the xsnap worker processes, with lines like:

`Cannot read netstring,  reading length prefix, fscanf`

I think this is the netstring reader in the worker, which gets an end-of-file indication rather than a netstring length prefix header.

I'm thinking that the worker process should silently exit when it sees this happen, instead of complaining. Having the parent process exit is a perfectly reasonable time for the worker process to exit: it's the least exceptional form of shutdown we've got.

**Comment by siarhei-agoric** [comment] 2024-08-23 21:55
Looks like xs_issueCommand() is the culprit:
[xsnap-worker.c:912](https://github.com/agoric-labs/xsnap-pub/blob/eef9b67da5517ed18ff9e0073b842db20924eae3/xsnap/sources/xsnap-worker.c#L912C1-L948C2)
```
static void xs_issueCommand(xsMachine *the)
{
	int argc = xsToInteger(xsArgc);
	if (argc < 1) {
		xsTypeError("expected ArrayBuffer");
	}

	size_t length = xsGetArrayBufferLength(xsArg(0));
	char* buf = xsToArrayBuffer(xsArg(0));
  
	recordTimestamp(); // before sending command to parent

	int writeError = fxWriteNetString(toParent, "?", buf, length);

	if (writeError != 0) {
		xsUnknownError(fxWriteNetStringError(writeError));
	}

	// read netstring
	size_t len;
	int readError = fxReadNetString(fromParent, &buf, &len);
	if (readError != 0) {
		xsUnknownError(fxReadNetStringError(readError));
	}
	recordTimestamp(); // after command-result received from parent

#if XSNAP_TEST_RECORD
	fxTestRecord(mxTestRecordJSON | mxTestRecordReply, buf, len);
#endif
	char command = *buf;
	if (len == 0 || command != '/') {
		xsUnknownError("Received unexpected command reply.");
	}

	xsResult = xsArrayBuffer(buf + 1, len - 1);
	free(buf);
}

```

Contrast it with how it is done in main():

[xsnap-worker.c:437](https://github.com/agoric-labs/xsnap-pub/blob/eef9b67da5517ed18ff9e0073b842db20924eae3/xsnap/sources/xsnap-worker.c#L437C1-L449C5)
```
		while (!done) {
[ . . . ]
			resetTimestamps();
			int readError = fxReadNetString(fromParent, &nsbuf, &nslen);
			recordTimestamp(); // after delivery received from parent
			int writeError = 0;

			if (readError != 0) {
				if (feof(fromParent)) {
					break;
				} else {
					fprintf(stderr, "%s\n", fxReadNetStringError(readError));
					c_exit(E_IO_ERROR);
				}
			}
[ . . . ]
		}
```

If I understand the main loop correctly, then xsnap-worker already provides a facility for the proper exit: `case 'q':`
[xsnap-worker.c:624](https://github.com/agoric-labs/xsnap-pub/blob/eef9b67da5517ed18ff9e0073b842db20924eae3/xsnap/sources/xsnap-worker.c#L624)
```
		char done = 0;
		while (!done) {
[ . . . ]
			resetTimestamps();
			int readError = fxReadNetString(fromParent, &nsbuf, &nslen);
			recordTimestamp(); // after delivery received from parent
			int writeError = 0;

			if (readError != 0) {
				if (feof(fromParent)) {
					break;
				} else {
					fprintf(stderr, "%s\n", fxReadNetStringError(readError));
					c_exit(E_IO_ERROR);
				}
			}
			char command = *nsbuf;
			// fprintf(stderr, "command: len %d %c arg: %s\n", nslen, command, nsbuf + 1);
			switch(command) {
			case 'R': // isReady
				fxWriteNetString(toParent, ".", "", 0);
				break;
[ . . . ]
			case 'q':
				done = 1;
				break;
[ . . . ]
			}
[ . . . ]
		}
```

Hence, the following fundamental questions arise:
- Does SIGTERM to a parent initiate an orderly shutdown with all of its pipes being properly closed?
- Is closing the parent side of the pipe the same as explicitly sending `q` command from the protocol standpoint?
- If a proper/safe exit mechanism is provided (`q`), then why it is not used by the parent to signal/request a worker shutdown when the parent itself is being shut down?
- If a parent dies/killed abruptly, is that not an abnormal situation?
- Should a worker also register a SIGTERM handler and exit gracefully when requested so by a party other than the parent?

**Comment by siarhei-agoric** [comment] 2024-09-16 21:29
I am hijacking this issue to transform it from "make xsnap-worker quiet" to "make xnap-worker error reports useful".

The issue is two-fold:
1. exit on EOF should be quiet only when the worker is in quiescent state (that is all of the work is done, and it is simply awaiting a new command from the parent).
2. broken pipes (as in EOF on read or SIGPIPE on write) should be detected and reported as such to worker's stderr.

The actual change had been implemented in [agoric-labs/xsnap-pub #53](https://github.com/agoric-labs/xsnap-pub/pull/53). This issue will track agoric-sdk side of things: xsnap version pulled in and automated testing.

**Comment by mhofman** [comment] 2024-09-16 23:26
> 1. exit on EOF should be quiet only when the worker is in quiescent state (that is all of the work is done, and it is simply awaiting a new command from the parent).

A well behaved kernel should send the `q` command for the worker to exit during normal operations.

However I believe that the kernel process does not attempt to cleanly exit its child workers when it gets terminated. As such silently exiting the worker while no command is in process is likely a good to have to avoid noisy service stop (which rely on kernel process termination in most cases).

**Comment by siarhei-agoric** [comment] 2024-09-16 23:55
> > 1. exit on EOF should be quiet only when the worker is in quiescent state (that is all of the work is done, and it is simply awaiting a new command from the parent).
> 
> A well behaved kernel should send the `q` command for the worker to exit during normal operations.
> 
> However I believe that the kernel process does not attempt to cleanly exit its child workers when it gets terminated. As such silently exiting the worker while no command is in process is likely a good to have to avoid noisy service stop (which rely on kernel process termination in most cases).

Based on my understanding of the [protocol description](https://github.com/agoric-labs/xsnap-pub/blob/eef9b67da5517ed18ff9e0073b842db20924eae3/xsnap/documentation/xsnap-worker.md) `q` is only acceptable when the worker is in quiescent state. That very state is also the safest time for the kernel to either exit or to be killed/crash from the worker perspective. That is why, I assume, the current xsnap-worker implementation treats `EOF` as equivalent of `q` for the worker in quiescent state. We should probably just update the protocol docs to make this explicit and official.

Note that there are no contradictions in our statements: yes, the kernel should make an effort to shut down the worker properly; yes, worker being quiet when its connection to the patent is terminated in the safest possible state is also desirable; finally, a worker should log something useful when its connection is terminated unexpectedly (that is in the middle of the conversation - a non-quiescent state).

**Closed as completed** 2024-09-25 19:00 UTC
Labels: enhancement, SwingSet, xsnap
