### ISSUE TITLE
Mysterious error when clean building on new machine

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#4248] opened 2022-01-05 21:54 UTC
I suspect the following errors are because of other things I need to install out-of-band, since I see it on a new M1 machine on fresh master prior to having installed the things I need to install. Thus, the fact of failure is not a bug. Rather, I'm reporting the obscurity of the error that I see, and the fact that there's no hint what the actual problem is.

Once I do install the remaining things, I'll come back here and explain what those were and what difference it makes. Depending on what I see, I may find out that the following errors have a different cause.

Attn @samsiegart 

```
(1):agoric-sdk(master)$ pushd packages/web-components/
~/src/ongithub/agoric/agoric-sdk/packages/web-components ~/src/ongithub/agoric/agoric-sdk
web-components(master)$ 
web-components(master)$ yarn test
yarn run v1.22.15
$ web-test-runner --coverage

test/agoric-petimage.test.js:

 🚧 Browser logs:
      Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.

test/agoric-petname.test.js:

 🚧 Browser logs:
      Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.

test/agoric-wallet-connection.test.js:

 🚧 Browser logs:
      Removing intrinsics.Symbol.useSetter
      Removing intrinsics.Symbol.useSimple
      Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
      Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
      Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.
      Element agoric-wallet-connection scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.
      locating locate CustomEvent { isTrusted: false }
      locating locate CustomEvent { isTrusted: false }
      bridged error Event {
        type: 'error',
        timeStamp: 1641419095364,
        target: WebSocket {
          listeners: {
            open: [Array],
            error: [Array],
            message: [Array],
            close: [Array],
            'server::message': [Array]
          },
          url: 'ws://localhost:8000/private/captp?accessToken=accessToken123',
          protocol: '',
          binaryType: 'blob',
          readyState: 3
        },
        srcElement: WebSocket {
          listeners: {
            open: [Array],
            error: [Array],
            message: [Array],
            close: [Array],
            'server::message': [Array]
          },
          url: 'ws://localhost:8000/private/captp?accessToken=accessToken123',
          protocol: '',
          binaryType: 'blob',
          readyState: 3
        },
        returnValue: true,
        isTrusted: false,
        eventPhase: 0,
        defaultPrevented: false,
        currentTarget: WebSocket {
          listeners: {
            open: [Array],
            error: [Array],
            message: [Array],
            close: [Array],
            'server::message': [Array]
          },
          url: 'ws://localhost:8000/private/captp?accessToken=accessToken123',
          protocol: '',
          binaryType: 'blob',
          readyState: 3
        },
        cancelable: false,
        canncelBubble: false,
        bubbles: false
      }
      locating locate CustomEvent { isTrusted: false }
      locating locate CustomEvent { isTrusted: false }
      locating locate CustomEvent { isTrusted: false }
      locating locate CustomEvent { isTrusted: false }

 ❌ AgoricWalletConnection > on getAdminBootstrap > goes to admin state once connected
      AssertionError: expected 'connecting' to equal 'bridged'
      + expected - actual
      
      -connecting
      +bridged
      
      at o.<anonymous> (test/agoric-wallet-connection.test.js:152:27)

Chrome: |██████████████████████████████| 3/3 test files | 16 passed, 1 failed

Code coverage: 60.29 %
View full coverage report at coverage/lcov-report/index.html

Finished running tests in 20.3s with 1 failed tests.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(1):web-components(master)$ 
```

**Comment by erights** [comment] 2022-01-05 21:56
Btw, I notice in the above output the identifier "canncelBubble" which looks like a misspelling. But neither "canncelBubble" nor "cancelBubble" seems to appear in agoric-sdk, so I'm confused. Where does this come from?

**Comment by samsiegart** [comment] 2022-01-05 22:00
> Btw, I notice in the above output the identifier "canncelBubble" which looks like a misspelling. But neither "canncelBubble" nor "cancelBubble" seems to appear in agoric-sdk, so I'm confused. Where does this come from?

Looks like the `mock-socket` package we're using to test `AgoricWalletConnection` https://github.com/thoov/mock-socket/blob/a146e097154ab7007dce0e65b68dc320f49a4675/src/event/event.js#L28

**Comment by samsiegart** [comment] 2022-01-05 22:04
By the way, which node version are you using?

This is the test that's failing, and it does seem a bit brittle https://github.com/Agoric/agoric-sdk/blob/master/packages/web-components/test/agoric-wallet-connection.test.js#L151

**Comment by erights** [comment] 2022-01-06 00:32
Good question. After switching to the new machine, I find I'm using node 14.15.3. I'll switch to 16 and try again. Thanks.

**Comment by erights** [comment] 2022-01-07 08:08
Upgrading to Node 16 didn't fix it. I checked my Chrome and already had an up-to-date one for arm. Installing latest Go for arm https://go.dev/dl/go1.17.6.darwin-amd64.pkg did seem to fix it.

Leaving this open because the error report provided no hint of what problem actually needed to be fixed.

**Comment by erights** [comment] 2022-01-07 22:57
After installing the latest Go, I did indeed have a successful run. However, the same problem has since reappeared, without my having changed anything I can think of that might be relevant. If true, this is an intermittent problem. :(

Attn @samsiegart @michaelfig

**Comment by michaelfig** [comment] 2022-01-08 04:06
> After installing the latest Go, I did indeed have a successful run. However, the same problem has since reappeared, without my having changed anything I can think of that might be relevant. If true, this is an intermittent problem. :(

I'm pretty sure this is just a flake and not a Node or Go version problem.

I'll take a look.

**Comment by michaelfig** [comment] 2022-01-08 05:09
> This is the test that's failing, and it does seem a bit brittle https://github.com/Agoric/agoric-sdk/blob/master/packages/web-components/test/agoric-wallet-connection.test.js#L151

There are attempts to prevent races by using `new Promise(resolve => setTimeout(resolve, 10))` in the test and its friends.

@erights can you try larger timeout values than just 10 in that file?

As far as brittleness, @samsiegart I think a more robust attempt would be to use the onState callback to detect when `bridged` was called, and do something more like:

```js
const delayP = new Promise(resolve => setTimeout(() => resolve('timeout'), 2000));
const onStateChangedToBridgedP = ...; // exercise for the reader
const result = await Promise.race([delayP, onStateChangedToBridgedP]);
expect(el.state).to.equal('bridged');
```

that way, timeouts can be significantly longer than the expected time, but the happy path will occur faster than having to wait until they elapse (as is necessary with delays).

**Comment by michaelfig** [comment] 2022-01-08 05:11
Also, @samsiegart, I never figured out how to mitigate:
>  Element agoric-wallet-connection scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.

If you have some time, could you PTAL?

**Comment by samsiegart** [comment] 2022-01-08 09:44
I created https://github.com/Agoric/agoric-sdk/pull/4257 which doesn't seem to flake on my machine, but I was unable to repro in the first place so it's a shot in the dark. I also fixed the https://lit.dev/msg/change-in-update warning (and verified tests still pass and that wallet+treasury still work).

**Comment by erights** [comment] 2022-01-08 23:35
> @erights can you try larger timeout values than just 10 in that file?

Today, everything seems to work again with the status quo timeout of 10. However, when I shorten the timeout things fail with the previous symptom.

Also, when I run branch #4257 sam-deflake , things work for me. Looking forward to seeing something that fixes #4248 merged. But I don't know enough to review #4257 nor the suggestions in the thread above. But having correctness depends on a delicate timeout smells like a poor standin for some other signal that should be reliable. Perhaps that suggested at https://github.com/Agoric/agoric-sdk/issues/4248#issuecomment-1007887799 or in #4257 . However, the comment at https://github.com/Agoric/agoric-sdk/pull/4257/files#r780651663 makes me nervous that we're still flakier than we understand, which is bad.

In the meantime, I will rebase on top of #4257 as long as that masks the problems adequately for my other work.

**Comment by michaelfig** [comment] 2022-01-09 01:01
> Today, everything seems to work again with the status quo timeout of 10. However, when I shorten the timeout things fail with the previous symptom.

Maybe your machine was just especially busy when it was failing with timeout of 10ms.

> Also, when I run branch #4257 sam-deflake , things work for me. Looking forward to seeing something that fixes #4248 merged. But I don't know enough to review #4257 nor the suggestions in the thread above. But having correctness depends on a delicate timeout smells like a poor standin for some other signal that should be reliable.

The basic problem is that we do have a reasonably reliable signal, but we are trying to test if the reliable signal really is reliable.  This is because we don't fully understand the behaviour and guarantees of the web components framework we're using (much like when Brian was working with SwingSet and trying to understand Node.js GC behaviour).

**Comment by erights** [comment] 2022-01-09 01:04
> but we are trying to test if the reliable signal really is reliable

Aha! That makes perfect sense. Thanks.

**Comment by samsiegart** [comment] 2022-01-09 06:08
The problem in part seems to be with the `mock-socket` library having an indeterministic delay in sending messages. You can see in the docs they wait 100ms before asserting https://www.npmjs.com/package/mock-socket.

But this isn't the entire issue, since in #4257, the `goes to admin state once connected` test still needs to wait at least 2 frames *after* the state change event is emitted for `el.state` to be consistently correct.

I think the best available solution might just be to bump up the delay. I don't think `await nextFrame()` is doing anything that deterministically hooks into the underlying logic beyond just adding another arbitrary delay. It seems that this flake was already hard to reproduce in the first place. In my experience, arbitrary delays are sometimes par for the course with webdriver testing unfortunately, as long as flakes are within a reasonable threshold (though I'm not sure if we have precedent for dealing with flaky tests in the sdk).

**Comment by samsiegart** [comment] 2022-01-09 06:16
And in particular, I believe the issue that necessitates the delay is that there is a chain of multiple callbacks that needs to happen around the socket/rendering logic. I don't see a way to hook into that with the testing framework.

**Comment by samsiegart** [comment] 2022-01-11 00:27
Merged https://github.com/Agoric/agoric-sdk/pull/4257 which passes in CI and should hopefully be less flaky locally, feel free to re-open this if you experience otherwise though. Also fixes the https://lit.dev/msg/change-in-update warning.

**Closed as completed by samsiegart** 2022-01-11 00:27 UTC
